# LED setup
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
# Startup effect (0 = solid color, 1 = breathing, 2 = spectrum, 3 = swirl)
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
# Optional: Adjust brightness, saturation, etc. for all LEDs
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=40
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0


CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_BACKLIGHT=y
### Power
CONFIG_ZMK_SLEEP=y # Enable deep sleep support
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_IDLE_TIMEOUT=120000

# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y